// <auto-generated />
using System;
using AirlineInventoryService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirlineInventoryService.Migrations
{
    [DbContext(typeof(AirlineDataContext))]
    [Migration("20220508160602_initials")]
    partial class initials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AirlineInventoryService.Models.AirlineModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDateTime");

                    b.Property<string>("FromPlace")
                        .IsRequired();

                    b.Property<string>("InstrumentType");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("SheduledDay");

                    b.Property<DateTime>("StartDateTime");

                    b.Property<decimal>("TicketCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ToPlace")
                        .IsRequired();

                    b.Property<int>("TotalBusinessClassSeats");

                    b.Property<int>("TotalNonBusinessClassSeats");

                    b.HasKey("Id");

                    b.ToTable("Flighttbl");
                });

            modelBuilder.Entity("AirlineInventoryService.Models.BookingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("emailId");

                    b.Property<string>("flightId");

                    b.Property<string>("flightName");

                    b.Property<string>("fromPlace");

                    b.Property<string>("mealType");

                    b.Property<int>("noOfSeats");

                    b.Property<string>("pnr");

                    b.Property<int>("seatNos");

                    b.Property<string>("toPlace");

                    b.Property<string>("userName");

                    b.HasKey("Id");

                    b.ToTable("FlightBooking");
                });

            modelBuilder.Entity("AirlineInventoryService.Models.User.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Gender");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.Property<bool>("isAdmin");

                    b.Property<string>("password")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AirlineService.DataModel.UserModelBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("gender");

                    b.Property<string>("userName");

                    b.HasKey("Id");

                    b.ToTable("UserList");
                });
#pragma warning restore 612, 618
        }
    }
}
